language: java
sudo: false
cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache
install:
  # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
  - if test ! -e $HOME/android-sdk-dl/tools_r25.2.5-linux.zip ; then curl https://dl.google.com/android/repository/tools_r25.2.5-linux.zip > $HOME/android-sdk-dl/tools_r25.2.5-linux.zip ; fi
  - unzip -q -n $HOME/android-sdk-dl/tools_r25.2.5-linux.zip -d $HOME/android-sdk

  # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
  - yes | $HOME/android-sdk/tools/bin/sdkmanager 'tools'
  - yes | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools'
  - yes | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;27.0.1'
  - yes | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-27'
env:
  - ANDROID_HOME=$HOME/android-sdk
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Pall,fullBuild -B -V
  - mvn test -B
